# Generated by Django 5.1.1 on 2024-10-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddlehub', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.UniqueConstraint(fields=('participant', 'event'), name='unique_RSVP'),
        ),
    ]
