# Generated by Django 5.1.1 on 2024-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddlehub', '0002_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Description of New Event'),
        ),
    ]
