# Generated by Django 5.1.1 on 2024-10-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddlehub', '0003_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
